AllCops:
  DisplayCopNames: true
  
Metrics/LineLength:
  Max: 200
Metrics/AbcSize:
  Max: 50
Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 100
Metrics/CyclomaticComplexity:
  Enabled: false	 
Style/TrailingWhitespace:
  Enabled: false
  